#!/bin/sh

# original https://codeberg.org/venenux/easybashadb
# This script is a best-effort attempt to manage your phones 
# and lauch scrcpy program and asome adb operations

######## PART 1 ######### init values toma de variables de entorno basicas

MSGCONSOLE="VENENUX phone manager; launcher usage is: \"easybashadb options ...\""
DSESSION=$(echo $DESKTOP_SESSION)	# detectando el tipo de escritorio
DDISPLAY=""
TTYTYPE=""
INVOKENAME=$0			# programa de invocacion, por este y la extension sabremos que emulador usar
ERROR=0
ERRORMSG=""
MUSL=0
ANDR=0
SUPT=0
DEVICELIST=""
DEVICEPHON=""
ADBCMD=""
ADBVER=""
SCRCMD=""
SCRVER=""

function ensure_commands() {

    if ! which -a which >/dev/null 2>&1; then
        ERROR=1
        ERRORMSG="$ERRORMSG error which command, .."
    fi

    tty >/dev/null 2>&1
    if [ $? -ne 0 ]; then
        ERROR=1
        ERRORMSG="$ERRORMSG missing 'tty' command, .."
    fi

    if ! which -a adb >/dev/null 2>&1; then
        ERROR=1
        ERRORMSG="$ERRORMSG missing 'adb' command (androit-tools/sdk), .."
    fi

    SCRCMD=$(find /usr/local /opt -type f -iname scrcpy -print | head -n1)

    if [ -z "$SCRCMD" ]; then
        ERROR=1
        ERRORMSG="$ERRORMSG missing 'scrcpy' command, .."
    fi

    if [ $ERROR -ne 0 ]; then
        echo "$ERRORMSG"
        exit 1
    fi

    ADBCMD=$(which adb | head -n1)
    ADBVER=$($ADBCMD --version | grep Version | cut -d' ' -f2 | cut -d. -f1)

    SCRCMD=$(find /usr/local /opt /usr/bin -type f -iname scrcpy -print | head -n1)
    SCRVER=$($SCRCMD --version | grep scrcpy | cut -d' ' -f2)
}

function ensure_graphics() {
    if [ ${#WAYLAND_DISPLAY} -gt 0 -o ${#DISPLAY} -gt 0 ]; then
        DDISPLAY=1
    else
        TTYTYPE=$(tty)
    fi
}

function ensure_dialog() {
    DIACMD=""
        if [ -n "$DSESSION" ]; then
            case "$DSESSION" in
                *kde*|*plasma*)
                    DIACMD=$(which kdialog | head -n1)
                    ;;
                *lxqt*|*dde*|*deepin*)
                    if [ -n "$WAYLAND_DISPLAY" ]; then
                        DIACMD=$(which qarma | head -n1)
                    else
                        DIACMD=$(which yad | head -n1)
                    fi
                    ;;
                *)
                    if [ -n "$WAYLAND_DISPLAY" ]; then
                        DIACMD=$(which yad | head -n1)
                    fi
                    ;;
            esac
        fi
        if [ -z "$DIACMD" ]; then
            DIACMD=$(which yad | head -n1)
        fi
        if [ -z "$DIACMD" ]; then
            DIACMD=$(which zenity | head -n1)
        fi
        if [ -z "$DIACMD" -o -z "$DDISPLAY" ]; then
            DIACMD=$(which dialog | head -n1)
            ERRORMSG="No dialog backend (no program to display graphical interface, please install zenity or yad or similar for..."
            ERROR=1
        fi
        case "$TTYTYPE" in
            *tty*)
                DIACMD=$(which dialog | head -n1)
                ERRORMSG="Running graphical session is mandatory"
                ERROR=1
                ;;
        esac
        DIACMD="${DIACMD##*/}"
}

function detect_musl() {
    MUSL=0
    local musldetect=""
    musldetect=$(ldd /bin/ls | grep 'musl')
    if [ -n "$musldetect" ]; then
        MUSL=1
    fi
}

function detect_andr() {
    ANDR=0
    local andrdetect=""
    andrdetect=$(adb shell getprop ro.build.version.sdk)
    if [ -n "$andrdetect" ]; then
        ANDR="$andrdetect"
    fi
}

function get_device_cable() {
    local deviceslist
    deviceslist=$(adb devices -l | sed 's/  */ /g' | cut -d' ' -f1 | tail -n +2)
    DEVICELIST=$deviceslist
}

function show_devices_phone_selector() {
    get_device_cable
    local menu
    local choice
    menu $DEVICELIST
    choice="$(0< "${dir_tmp}/${file_tmp}" )"
    DEVICEPHON=$choice
    clean_temp
}

function main_menu_always_for_phone() {
    show_devices_phone_selector
    while [ -z "$DEVICEPHON" ]; do
        show_devices_phone_selector
    done
    ADB="$ADBCMD" $SCRCMD -s $DEVICEPHON
}

function main() {

    export supermode="$DIACMD"
    export supertitle="SCRSCPY phone selector manager"
    export supericon="system"
    export supercontext="windows" # this is gui only program.. and need opengl for some operatinos
    source easybashgui

    main_menu_always_for_phone

    clean_temp

}

ensure_commands

ensure_graphics

ensure_dialog

if [ $ERROR -ne 0 ]; then
    echo "$ERRORMSG"
    exit 1
fi

main
