#! /bin/sh

# original https://codeberg.org/venenux/easybashadb
# This script is a best-effort attempt to manage your phones 
# and lauch scrcpy program and asome adb operations

ERROR=0
ERRORMSG=""
MUSL=0
ANDR=0

function ensure_commands() {

    if ! which -a which >/dev/null 2>&1; then
        ERROR=1
        ERRORMSG="$ERRORMSG error which command, .."
    fi

    tty
    if [ $? -ne 0 ]; then
        ERROR=1
        ERRORMSG="$ERRORMSG missing 'tty' command, .."
    fi

    if ! which -a adb >/dev/null 2>&1; then
        ERROR=1
        ERRORMSG="$ERRORMSG missing 'adb' command (androit-tools/sdk), .."
    fi

    SCRCMD=$(find /usr/local /opt -type f -iname scrcpy -print | head -n1)

    if [ -z "$SCRCMD" ]; then
        ERROR=1
        ERRORMSG="$ERRORMSG missing 'scrcpy' command, .."
    fi

    if [ $ERROR -ne 0 ]; then
        echo "$ERRORMSG"
        exit 1
    fi

    ADBCMD=$(which adb | head -n1)
    ADBVER=$($ADBCMD --version | grep Version | cut -d' ' -f2 | cut -d. -f1)

    SCRCMD=$(find /usr/local /opt /usr/bin -type f -iname scrcpy -print | head -n1)
    SCRVER=$($SCRCMD --version | grep scrcpy | cut -d' ' -f2)
}

function detect_musl() {
    MUSL=0
    musldetect=""
    musldetect=$(ldd /bin/ls | grep 'musl')
    if [ -n "$musldetect" ]; then
        MUSL=1
    fi
}

function detect_andr() {
    ANDR=0
    andrdetect=""
    andrdetect=$(adb shell getprop ro.build.version.sdk)
    if [ -n "$andrdetect" ]; then
        ANDR="$andrdetect"
    fi
}

function main() {


}

ensure_commands

main
